import Image from 'next/image'
import Head from 'next/head'

export async function getServerSideProps() {
  const res = await fetch("http://localhost:8000").then(x => x.json());
  return {
    props: {
      status: res.status,
    }
  }
}

export default function Home({status}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.JS!</a>
        </h1>
        <div>Status is: {status}</div>
      </main>
    </div>
  )
}
